// Hey, this component was created only for testing purposes. it wouldnt be returned or used at all.

const fakeContent = () => {
  
    return `                <table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width: 100%;min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" width="100%" class="mcnTextContentContainer">
    <tbody><tr>
 
        <td valign="top" class="mcnTextContent" style="padding: 0px 18px 9px;line-height: 150%;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;word-break: break-word;color: #111111;font-family: 'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size: 18px;text-align: left;">
 
 
 
            <h1 class="null" dir="ltr" style="text-align: center;display: block;margin: 0;padding: 0;color: #111111;font-family: 'Merriweather Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size: 26px;font-style: normal;font-weight: bold;line-height: 125%;letter-spacing: normal;">The Secrets of High-Performing DevOps teams</h1>
            <br>
            <div dir="ltr" style="text-align: justify;"><span style="font-size:15px"><span style="font-family:trebuchet ms,lucida grande,lucida sans unicode,lucida sans,tahoma,sans-serif">Ultra-fast innovation holds the key for conglomerates like <a href="https://hackernoon.com/tagged/apple" target="_blank" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #0000EE ;font-weight: bold;text-decoration: underline;">Apple</a>, <a href="https://hackernoon.com/tagged/microsoft" target="_blank" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #0000EE ;font-weight: bold;text-decoration: underline;">Microsoft</a>, and <a href="https://hackernoon.com/tagged/china" target="_blank" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #0000EE ;font-weight: bold;text-decoration: underline;">Tencent</a> known as the pacesetters in the modern markets. However, they all <a href="https://hackernoon.com/how-to-reduce-software-development-costs-h3153t9u" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #0000EE;font-weight: bold;text-decoration: underline;">faced challenges</a> that are typical for established companies. For the most obvious examples, Laggard, tricky releases and a gap between dev and ops plugged them into implementing a <a href="https://hackernoon.com/how-to-make-a-devops-strategy-pk153uyb" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #0000EE;font-weight: bold;text-decoration: underline;">radical DevOps strategy</a>.</span></span></div>
            <br>
            <div dir="ltr" style="text-align: justify;"><span style="font-size:15px"><span style="font-family:trebuchet ms,lucida grande,lucida sans unicode,lucida sans,tahoma,sans-serif">Before <a href="https://hackernoon.com/how-the-devops-model-redefines-qa-best-practices-8f1t3t7u" target="_blank" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #0000EE ;font-weight: bold;text-decoration: underline;">Superman aka DevOps</a> came on stage, organizations used to have walled-off teams that had little to no idea of what was going on at other departments.  As a result, developers would spend several months’ worth of work and pass their <a href="https://hackernoon.com/how-the-devops-model-redefines-qa-best-practices-8f1t3t7u" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #0000EE;font-weight: bold;text-decoration: underline;">code on to QA</a>. Guess what came next? Yep, <a href="https://hackernoon.com/how-goji-investments-enhances-developer-experience-via-observability-641f3w2q" target="_blank" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #0000EE ;font-weight: bold;text-decoration: underline;">bugs, bugs, and...lots of bugs</a>. Surely, that classic cop-out “It works fine on my computer” was a <a href="https://hackernoon.com/a-z-of-devops-managing-multiple-environments-with-the-help-of-these-tools-n6x3thm" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #0000EE;font-weight: bold;text-decoration: underline;"> go-to for developers</a>. As for Ops, they would <a href="https://hackernoon.com/4-skills-you-need-to-become-a-distinguished-developer-ly2d3tjl" target="_blank" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #0000EE ;font-weight: bold;text-decoration: underline;">get the same lame code</a> lame code, swallow their pride, and <a href="https://hackernoon.com/9-functional-programming-concepts-everyone-should-know-uy503u21" target="_blank" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #0000EE ;font-weight: bold;text-decoration: underline;">clean up the mess</a>.</span></span></div>
            <br>
            <div dir="ltr" style="text-align: center;"><span style="font-family:georgia,times,times new roman,serif"><span style="font-size:17px"><a href="https://hackernoon.com/10-best-object-oriented-online-programming-and-design-courses-2020-updated-wv83uff" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #111111;font-weight: bold;text-decoration: underline;"><img data-file-id="1168" alt="" height="220" src="https://gitlab.com/hackernoon/creative/-/raw/master/newsletters/memes/2020/october/24.10/image4.gif" style="border: 0px initial;width: 220px;height: 220px;margin: 0px;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;" width="220"></a></span></span></div>
            <br>
            <div dir="ltr" style="text-align: justify;"><span style="font-size:15px"><span style="font-family:trebuchet ms,lucida grande,lucida sans unicode,lucida sans,tahoma,sans-serif">Luckily, we have the <a href="https://hackernoon.com/the-highest-paying-jobs-in-america-dlj3uaw" target="_blank" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #0000EE ;font-weight: bold;text-decoration: underline;">DevOps</a> approach that allows companies to keep the <a href="https://hackernoon.com/10-best-object-oriented-online-programming-and-design-courses-2020-updated-wv83uff" target="_blank" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #0000EE ;font-weight: bold;text-decoration: underline;">delivery process</a> in full gear and improve products at a <a href="https://hackernoon.com/10-best-object-oriented-online-programming-and-design-courses-2020-updated-wv83uff" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #0000EE;font-weight: bold;text-decoration: underline;">supersonic speed</a>. However, implementing a DevOps philosophy is not enough. Only <a href="https://hackernoon.com/rework-costs-your-company-millions-how-to-cut-back-nwq3wdv" target="_blank" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #0000EE ;font-weight: bold;text-decoration: underline;">high-performing DevOps teams</a> that have mastered some key capabilities can <a href="https://hackernoon.com/tagged/jfrog" target="_blank" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #0000EE ;font-weight: bold;text-decoration: underline;">deliver faster</a>, more accurately, and with <a href="https://hackernoon.com/data-persistent-prometheus-grafana-intergration-with-jenkins-5d263uvv" target="_blank" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #0000EE ;font-weight: bold;text-decoration: underline;">less downtime</a>. We have curated some secrets that differentiate <a href="https://hackernoon.com/ryan-dawson-on-open-source-tools-and-mlops-a-noonie-nom-interview-1hcy3u7x" target="_blank" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #0000EE ;font-weight: bold;text-decoration: underline;">DevOps leaders from laggards</a>.</span></span></div>
 
 
            <br>
            <div dir="ltr" style="text-align: center;"><span style="font-family:georgia,times,times new roman,serif"><span style="font-size:17px"><a href="https://hackernoon.com/how-to-build-an-effective-and-sustainable-on-call-schedule-for-your-team-3p11a3txy" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #111111;font-weight: bold;text-decoration: underline;"><img data-file-id="101168" alt="" height="220" src="https://gitlab.com/hackernoon/creative/-/raw/master/newsletters/memes/2020/october/24.10/image1.gif" style="border: 0px initial;width: 220px;height: 220px;margin: 0px;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;" width="220"></a></span></span></div>
 
 
        </td>
    </tr>
 </tbody></table>`; 
   
 }
 
 
 export default fakeContent;
 